version: "3"
services:
  api:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.local
    env_file:
      - ./local.env
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app
    depends_on:
      - database
  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./etc/data/db:/data/db
  test:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    env_file:
      - ./local.env
    volumes:
      - /app/node_modules
      - .:/app
    depends_on:
      - database
