version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    environment:
      - LOCAL=true
      - NODE_ENV=development
      - PORT=3000
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app
